dist: xenial
addons:
  apt:
    sources:
    - sourceline: deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable
        jdk1.8
      key_url: https://bazel.build/bazel-release.pub.gpg
    packages:
    - openjdk-8-jdk
    - bazel
script: bazel test //pkg/... && bazel build //src:libgo_fdw.so
deploy:
  provider: script
  script: bash scripts/docker-push.sh
  on:
    branch: master
env:
  global:
  - secure: xeYIEoq2X/x9k9La2tGxKdfd131rmCf5uEbruqpP+2Dvynybj9l89VSutsJ9/6fGXHUnQorunEbYNDMadqh3p/I9jHKerxEuKgs4BWFVsz16PUrqltamjwA7+Rn8icZkhOZsfzcXeH/RPxljYrfSjyI2FyCuLAMhuk/IPxdgF+KcRC6rHojB9++HvMrEyg97yVKxJa+8t0tLlhq87Jfy0rn9wPJwyWLrRNiV4ZQ3YygJsVY2d3FAOYcxZu/iuAwowMDRs8cXu7903SMapYd5y4xcil9PgCvMi4VUvJiTkxrG4jK/qH5GZB7C7g1DLqnuhzs3Vz8/eAX8pnH54IqEBjEmHVMoO7nJrqKuqtSWkklNIqvG5VXpaJLTDjGOWVSDSxvhhH/agbQzDTC9+cS6xryTdStw3EgSp2sK9/gQSd+ZvYQEKSrCA7eWQhtwWC7n78pT3VWy/R72cHQgFzDl8nsZxN45MLt7qb25ASNljQrkM1im/k47SuJtk3PZ4k7DjaBlcmAIYaptG7MjFrn+fUNFKuEYJ0/CvJ4QlEYOkoTkpgOmkWDJ68+f62UUW71TruEkJ6Ww6fafOkR2W8+CQMbdLz4hrm2LyTaVx7Tk7BPOIczRt5NR7YxezKBIqFT833GNgdln7CySdewPGvonXLdaFd8XBW8Fj0Hl4kBq98M=
  - secure: Cb3dz7ftDKGwSd1V2nteHH42JMAAWLipJi+ry2wzCmlYXfh0+IXHgxaH0O24v9Q8iayOKflv8thfXaAq46Y12ygr2RgNB6yojlHv6+rlc7IL9JkiJRxe7wgsNfK8g4tF4vPDa4ARLK3uammw8yXGSA7+lVmWBpq19LMo9d5TIrZfgPapf+Roc/eVQCkX8HlJ+MKnv8oRufOpk0lS/28XpWkqsLPqSdH9D9zyFcT9FDxjE0ZSCQhfPZ2AEmZGjs8mCTI14J4AAgxpUGFjKO+vtDG3LjQy9+zsuzbj4u7DYhcxmdHVIDo41BeTDTehJyzX11QXlTbe6V4epBcZNPujFUkvedcL6r/PHFPmz2e0fLH2rPkGV20z8vFt4xk1c/afGZu2RbbJnQM/H9gDu6awL7gJFnX86rv2q3BjGGklRInkjsNPQbZgstun+wNkbx0eE5FEe6hgMtgF1X1wgTEqX7lb7TTZKpZi6IhtUSaDQk4JfjO0BsUJq8xkMC18OX2e/r+BWncrH05UDwDW9RzXTpC9HL9fpb2ZcbWkmEMBlqmsNtwiVTygpHgfWyQXOibQQ8wk8hw45hIEy1UfiEp4jdS1ga2dOa2Eie+exykFR/yrz/SvRXR8NfgWBHgDrzfSVvX5nrUowRt0hgfIIK2BuDUqB3wufQ5mBXIa1+z2Chc=
